pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packageName: 'MakoIoT.Device.Utilities.ICalParser'

resources:
  repositories:
    - repository: templates
      type: github
      name: CShark-Hub/Mako-IoT.Tools
      endpoint: CShark-Hub

steps:
- template: azure-pipelines-templates/azure-pipelines-publish-template.yml@templates